routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'AgendaController@index')->name('home');

// Rotas do CRUD

Route::middleware('auth')->group(function(){
    Route::resource('agenda', 'AgendaController');
});

app/Agenda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Agenda extends Model
{
    protected $fillable = [ 'nome','sexo','profissao','link_social','status' ];
    protected $table = 'contatos';
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AgendaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Agenda;

class AgendaController extends Controller
{

    private $agenda;
    
    public function __construct(Agenda $agenda){
        
        $this->agenda = $agenda;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contatos = $this->agenda->orderBy('id', 'DESC')->paginate(5);
        return view('agenda.index', compact('contatos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('agenda.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $data = $request->all();
            //Criado com Mass Assignment
            $agenda = $this->agenda->create($data);

            flash('Contato salvo com sucesso!')->success();
            return redirect()->route('agenda.index');

        } catch(\Exception $e) {
            if(env('APP_DEBUG')) {
                flash($e->getMessage())->warning();

                return redirect()->back();
            }

            flash('Contato não foi criada, tente novamente ou chame o suporte!')->warning();
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try{
            $agenda = $this->agenda->findOrFail($id);

            return view('agenda.edit', compact('agenda'));

        } catch(\Exception $e) {
            if(env('APP_DEBUG')) {
                flash($e->getMessage())->warning();
                return redirect()->back();
            }

            flash('Post não encontrado...')->warning();
            return redirect()->back();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
            $data = $request->all();

            $agenda = $this->agenda->findOrFail($id);
            $agenda->update($data);

            flash('Contato atualizado com sucesso!')->success();
            return redirect()->route('agenda.index');

        } catch(\Exception $e) {
            if(env('APP_DEBUG')) {
                flash($e->getMessage())->warning();
                return redirect()->back();
            }
            flash('Contato não foi atualizado...')->warning();
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {

            $agenda = $this->agenda->findOrFail($id);
            $agenda->delete();

            flash('Contato removido com sucesso!')->success();
            return redirect()->route('agenda.index');

        } catch(\Exception $e) {
            if(env('APP_DEBUG')) {
                flash($e->getMessage())->warning();
                return redirect()->back();
            }

            flash('Contato não pode ser removido...')->warning();
            return redirect()->back();
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/agenda/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="col-12">
            <h4>Adicionando Novo Contato</h4>
            <a href="{{route('agenda.index')}}" class="float-right btn btn-secondary">Retornar</a>
        </div>
        <br>
        <form action="{{route('agenda.store')}}" method="post">
        @csrf


            <div class="form-group">
                <label for="nome">Nome</label>
                <input type="text" name="nome" id="nome" class="form-control">
            </div>

            <div class="form-group">
                <label for="sexo">Sexo</label>                
                <select name="sexo" id="sexo" class="form-control">
                    <option value="F">Feminino</option>
                    <option value="M">Masculino</option>
                </select>
            </div>

            <div class="form-group">
                <label for="profissao">Profissão</label>
                <input type="text" name="profissao" id="profissao" class="form-control" placeholder="Analista de Sistema, Médico, Pedreiro, Padeiro ou etc.">
            </div>

            <div class="form-group">
                <label for="link_social">Link Social</label>
                <input type="text" name="link_social" id="link_social" class="form-control" placeholder="Seu instagran, facebook, site pessoal, linkdin ou etc.">
            </div>

            <div class="form-group">
                <label for="status">Status</label>                
                <select name="status" id="status" class="form-control">
                    <option value="ativo">Ativo</option>
                    <option value="inativo">Inativo</option>
                </select>
            </div>

            <button type="submit" class="btn btn-success">Salvar</button>
        </form>
    </div>

@endsection

resources/views/agenda/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="col-12">
            <h4>Editando Novo Contato</h4>
            <a href="{{route('agenda.index')}}" class="float-right btn btn-secondary">Retornar</a>
        </div>
        <br>
        <form action="{{route('agenda.update', ['agenda' => $agenda->id])}}" method="post">
        @csrf
        @method("PUT")
            <div class="form-group">
                <label for="nome">Nome</label>
                <input type="text" name="nome" id="nome" value="{{$agenda->nome}}" class="form-control">
            </div>

            <div class="form-group">
                <label for="sexo">Sexo</label>                
                <select name="sexo" id="sexo" class="form-control">
                    <option value="F" {{$agenda->sexo == 'F' ? 'selected' : ''}}>Feminino</option>
                    <option value="M" {{$agenda->sexo == 'M' ? 'selected' : ''}}>Masculino</option>
                </select>
            </div>            

            <div class="form-group">
                <label for="profissao">Profissão</label>
                <input type="text" name="profissao" id="profissao" value="{{$agenda->profissao}}" class="form-control" placeholder="Analista de Sistema, Médico, Pedreiro, Padeiro ou etc.">
            </div>

            <div class="form-group">
                <label for="link_social">Link Social</label>
                <input type="text" name="link_social" id="link_social" value="{{$agenda->link_social}}" class="form-control" placeholder="Seu instagran, facebook, site pessoal, linkdin ou etc.">
            </div>

            <div class="form-group">
                <label for="status">Status</label>                
                <select name="status" id="status" class="form-control">
                    <option value="ativo" {{$agenda->status == 'ativo' ? 'selected' : ''}}>Ativo</option>
                    <option value="inativo" {{$agenda->status == 'inativo' ? 'selected' : ''}}>Inativo</option>
                </select>
            </div>

            <button type="submit" class="btn btn-success">Salvar Edição</button>
        </form>
    </div>

@endsection

resources/views/agenda/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="col-12">
            <a href="{{route('agenda.create')}}" class="btn btn-success">Adicionar Contato</a>
        </div>
        <br>
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Sexo</th>
                    <th>Profissão</th>
                    <th>Link Social</th>
                    <th>Status</th>
                    <th>Criado</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @forelse($contatos as $contato)
                <tr>
                    <td>{{$contato->id}}</td>
                    <td>{{$contato->nome}}</td>
                    <td>{{$contato->sexo}}</td>
                    <td>{{$contato->profissao}}</td>
                    <td>{{$contato->link_social}}</td>
                    <td>{{$contato->status}}</td>
                    <td>{{$contato->created_at}}</td>
                    <td>
                        <a href="{{route('agenda.show', ['agenda' => $contato->id ])}}" class="btn btn-secondary">Editar</a>                        
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#excluirContato">Excluir</button>

                        <div class="modal" tabindex="-1" role="dialog" id="excluirContato">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Excluir Contato</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <h4>Deseja realmente exlcuir contato?</h4>
                                </div>
                                <div class="modal-footer">                                    
                                    <form action="{{route('agenda.destroy', ['agenda' => $contato->id])}}" method="post">
                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger">Excluir</button>
                                    </form> 
                                </div>
                                </div>
                            </div>
                        </div>        

                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="7">
                        <h2>Nenhum contato encontrado!</h2>
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
        {{ $contatos->links() }}
    </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>
    
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Adriana V - CRUD') }}
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                
            </ul>
            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </nav>
    
    <br>

    <main class="py-5 container">

        @include('flash::message')

        @yield('content')
    </main>
    
</body>
</html>